#!/bin/bash
#SBATCH --nodes 1 --ntasks 2 --mem 2gb --time 2:00:00

my_data = 3300000333.a.ko.txt

awk '{ if($3 >= 80 && $9 <= 1e-06) { print }}' my_data > filtered.ko.txt

cut -f1,3 filtered.ko.txt > my_data_cleaned.ko.txt

awk '{gsub("KO:","",$2)}1' my_data_cleaned.ko.txt > honeybee_microbiome_ko.txt



